<?php
/** 
 * @NEW New<br/>Link
 * @BTN2 Copy<br/>Section
 * @BTN3 ReDraw<br/>Section
 * @BTN4 ?
 * @BTN5 New
 * @BTN6 Load Blueprint
 * @BTN7 Save
 * @BTN8 Load Box
 * @DELETEBTN Remove<br/>Section
 * @blah
 */
class xLoginLang {
	// Used for Complex values.
	var $_LANG = array(
		'emails'		=> array(
			'key' => array(
				'sub' => " has given you a Key to ",
				'msg' => "Hello"
			)
		),
		'ICON' => 'fa-key',
		'JUMBO' => array(

			'HEAD' => 'Captain\'s Blog',
			'QUOTE' => 'Here is ware yar set a path for ye vistors.',
			'BTN'	=> array(
				
				'windKeys'	=> array(
					'a' => '<i class="fa fa-flag"></i>  Entry Key  &nbsp; ',
					'class' => 'btn-info'
				),
				'earthKeys'	=> array(
					'a' => '<i class="fa fa-leaf"></i>  Green Key &nbsp; ',
					'class' => 'btn-success'
				),
				'waterKeys'	=> array(
					'a' => '<i class="fa fa-user-md"></i>  Blue Key &nbsp; ',
					'class' => 'btn-primary'
				),
				'fireKeys'	=> array(
					'a' => '<i class="fa fa-fire"></i>  Red Key &nbsp; ',
					'class' => 'btn-danger'
				),
				'masterKeys'	=> array(
					'a' => '<i class="fa fa-key"></i> Master Key &nbsp; ',
					'class' => 'btn-warning'
				),
			)
		),
		'keys' => array(
			'ICON' => 'fa-key',
			'JUMBO' => array(
				'HEAD' => 'Keys to the Kingdom',
				'QUOTE' => 'Create Keys to invite those whom you wish to grant such access to your domain.',
				'BTN'	=> array(
					'shelves'	=> array(
						'a' => '<i class="fa fa-book"></i> Catalog &nbsp; ',
						'class' => 'btn-info'
					),
					//'products'	=> '<i class="fa fa-coffee"></i> Products & Serives &nbsp; ',
					'orders'	=> array(
						'a' => '<i class="fa fa-truck"></i> Orders &nbsp; ',
						'class' => 'btn-success'
					)
				),
				'catalog' => array(
					''
				)
			)
		),
		'masterKeys' => array(
			'ICON' => 'fa-key',
			'JUMBO' => array(
				'HEAD' => 'Master Key',
				'QUOTE' => 'Master Keys grants an All-Access Pass across your whole domain! ',
				 
			)
		),
		'masterKey' => array(
			'ICON' => 'fa-key',
			'JUMBO' => array(
				'HEAD' => 'Master Key',
				'QUOTE' => 'Master Keys grants an All-Access Pass across your whole domain! ',
				 
			)
		),
		'fireKeys' => array(
			'ICON' => 'fa-fire',
			'JUMBO' => array(
				'HEAD' => 'Fire Kingdom',
				'QUOTE' => 'Create Keys to invite those whom you wish to grant such access to your domain.',
				 
			)
		),
		'earthKeys' => array(
			'ICON' => 'fa-globe',
			'JUMBO' => array(
				'HEAD' => 'Earth Kingdom',
				'QUOTE' => 'These keys grant the users the strength to upload and mangage large files.',
				 
			)
		),
		'waterKeys' => array(
			'ICON' => 'fa-heart',
			'JUMBO' => array(
				'HEAD' => 'Water Kingdom',
				'QUOTE' => 'Create Keys to invite those whom you wish to grant such access to your domain.',
				 
			)
		),
		'windKeys' => array(
			'ICON' => 'fa-flag',
			'JUMBO' => array(
				'HEAD' => 'Wind Kingdom',
				'QUOTE' => 'Create Keys to invite those whom you wish to grant such access to your domain.',
				 
			)
		)

	);
}
?>