<?php
/** 
 */
class xWwwSetupLang {
	// Used for Complex values.
	var $_LANG = array(
		'CONFIG' => array(
			'SITE' => array(
				'NAME'      => 'My SuperDom Site',
				'MOTO'      => 'A Network of Sites!',
				'COPYRIGHT' => 'SuperDomX &#copy; 2010~13'
			)
		),
		'ICON' => 'fa-magic',
		'JUMBO' => array(

			'HEAD' => 'www Paper',
			'QUOTE' => 'Here is where you can control the look and feel of your websites\'s pages.',
			'BTN'	=> array(
				'bootstrap'	=> array(
					'a' => '<i class="fa fa-magic"></i> Paper Portal &nbsp; ',
					'class' => 'btn-danger'
				),
				'buildHtml'	=> array(
					'a' => '<i class="fa fa-html5"></i> HTML &nbsp; ',
					'class' => 'btn-warning'
				),
				'buildJs'	=> array(
					'a' => '<i class="fa fa-coffee"></i> Javascript &nbsp; ',
					'class' => 'btn-info'
				),
				'buildCss'	=> array(
					'a' => '<i class="fa fa-css3"></i> CSS  &nbsp; ',
					'class' => 'btn-success'
				)
			)
		),
	);
}
?>